### ISSUE TITLE
Conflict with jquery ui slider

### ISSUE THREAD

**Issue by execut** [kartik-v/yii2-slider#12]
While attached jquery ui, yii2-slider is not created, widget named slider is already exist.
Bootstrap slider is designed for this here:
https://github.com/seiyria/bootstrap-slider/blob/master/js/bootstrap-slider.js#L1455
Used other function name bootstrapSlider
But JuiAsset must registered before yii2-slider asset

**Comment by execut** [comment]
Bootstrap slider is designed for this here:
https://github.com/seiyria/bootstrap-slider/blob/master/js/bootstrap-slider.js#L1455
Used other function name bootstrapSlider

**Comment by kartik-v** [comment]
A new boolean property `pluginConflict` has been added which defaults to `false`.

Set it to `true` if you are using with jquery UI and you are done.

**Comment by execut** [comment]
very fast, thank you=)

**Comment by BenasPaulikas** [comment]
After setting `pluginConflict` to true 

I get this JS error

```jQuery(...).bootstrapSlider is not a function```

In source code I see this:

```jQuery('#xyz').bootstrapSlider(bootstrapSlider_b6216955);```

**Comment by yaroslavolekh** [comment]
i've got the save error: jQuery(...).bootstrapSlider is not a function

**Comment by timsabruno** [comment]
If you get .bootstrapSlider is not a function you have a problem in loading the dependencies. 
Simply:
`use kartik\slider\Slider;
Yii::$app->assetManager->bundles['kartik\base\WidgetAsset'] = [
'depends' => ['kartik\slider\SliderAsset']
];
Yii::$app->assetManager->bundles['kartik\slider\SliderAsset'] = [
'depends' => ['yii\jui\JuiAsset']
];
Yii::$app->assetManager->bundles['yii\jui\JuiAsset'] = [
'depends' => ['yii\bootstrap\BootstrapPluginAsset']
];`
