### ISSUE TITLE
Formatter property is not passed correctly to plugin

### ISSUE THREAD

**Issue by ehmPlankje** [kartik-v/yii2-slider#14]
According to the documentation of the Bootstrap Slider plugin at https://github.com/seiyria/bootstrap-slider the `formatter` property provides a callback function. However, the slider plugin passes the `formatter` property as a string instead of as an anonymous function. This results in an `Uncaught TypeError: this.options.formatter is not a function` on the client.

Code to reproduce the bug:
```
echo \kartik\slider\Slider::widget([
    'name' => 'test',
    'pluginOptions' => [
        'formatter' => 'function(value) { console.log(value); }'
    ],
]);
```

**Comment by kartik-v** [comment]
It is not a bug but the method you are using in Yii to pass js expressions is wrong. Read yii docs. In yii you must use yii\helpers\JsExpression to escape strings as js expressions when they are sent as json encoded options.

**Comment by ehmPlankje** [comment]
Thanks for your reply. The reason why I assumed this was the proper syntax is because your plugin employs the same syntax for the methods defined under `pluginEvents`. Perhaps you could clarify this deviation from the standard syntax in your documentation?

Thanks for all the great plugins you provide the community with; really appreciate your work!

**Comment by kartik-v** [comment]
Plugin events always will be JS expressions (js functions). So even if someone sets a string, the code has been built to force convert it to JS expr. However this is not true for plugin options. It depends on each plugin.

**Comment by kartik-v** [comment]
The way its coded in Krajee Widgets is this way. Plugin events are always JS expressions (i.e JS function callbacks). So even if someone sets them as a string, the Krajee widget code has been built in such a way that it will force convert that to a yii JS expression. 

However this is not true for plugin options. Each plugin has its own way of identifying each plugin option. It cannot be force set to a string, integer or js expression. It has to be done by each developer based on the plugin's need.
