### ISSUE TITLE
Question: Composer warnings

### ISSUE THREAD

**Issue by HankBrown** [kartik-v/yii2-slider#21]
```
require.kartik-v/yii2-slider : unbound version constraints (dev-master) should be avoided
require.kartik-v/yii2-widget-colorinput : unbound version constraints (*) should be avoided
require.kartik-v/yii2-widget-sidenav : unbound version constraints (*) should be avoided
```
I am in composer hell this morning. Nothing to do with kartik I trust, but in the course of debugging I find these warnings produced by "composer diagnose".

I don't understand much of composer, but this warning makes sense to me. One day I will run composer update and pull in updates from kartik that have breaking changes for me, isn't that right?

The only way for me to future-proof my updates is to clone (freeze) your repos? Or to never run a blanket composer update? Not sure what people are doing for this. Not sure why kartick has no versioning?

**Comment by kartik-v** [comment]
All packages here have versions.

This is a config you as a app developer need to do on your app. You need to actually check this from your end in your yii 2 app composer.json for what version dependencies you need to install each such package.
